name: Benchmark

on:
  pull_request:
  push:
    branches:
      - '*'

  repository_dispatch:
    types: [push-in-khepri]

jobs:
  Benchmark:
    name: Benchmark Khepri
    runs-on: ubuntu-latest

    steps:
      - name: Checkout khepri-benchmark
        uses: actions/checkout@v3

      - name: Checkout khepri
        uses: actions/checkout@v3
        with:
          repository: rabbitmq/khepri
          # _checkouts/<dependency> overrides the dependency version defined in
          # rebar.config for a rebar3 project
          # https://rebar3.readme.io/docs/dependencies#checkout-dependencies
          path: _checkouts/khepri

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24

      - name: Compile
        run: rebar3 escriptize

      - name: Benchmark
        run: _build/default/bin/khepri-benchmark

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
